version: '3.8'

services:
  web:
    image: laptopui-prod
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
        - NPM_CONFIG_LOGLEVEL=verbose
    ports:
      - "3000:3000"
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_JWT_SECRET=${NEXT_PUBLIC_JWT_SECRET}
      - JWT_SECRET=${NEXT_PUBLIC_JWT_SECRET}
    dns:
      - 8.8.8.8
      - 8.8.4.4

  dev:
    image: laptopui-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_JWT_SECRET=${NEXT_PUBLIC_JWT_SECRET}
      - JWT_SECRET=${NEXT_PUBLIC_JWT_SECRET}

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16 