version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:5000/api
    depends_on:
      - backend

  backend:
    build:
      context: ./src/server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=your_mongodb_url
      - JWT_SECRET=your_jwt_secret
      - PORT=5000
    volumes:
      - ./src/server:/app
      - /app/node_modules

networks:
  default:
    driver: bridge 