services:
  - type: web
    name: laptopui-backend
    env: node
    buildCommand: npm run render:build
    startCommand: npm run render:start
    envVars:
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
    healthCheckPath: /health 