services:
  - type: web
    name: laptopui-backend
    env: node
    buildCommand: cd src/server && npm install && npm run build
    startCommand: cd src/server && npm start
    envVars:
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
    healthCheckPath: /health 